### ISSUE TITLE
Required Markers not Shown in IE

### ISSUE THREAD

**Issue by freinhard** [OneGov/plonetheme.onegov#165]
In Internet Explorer Version 11 the required markers are not visible.

![bildschirmfoto 2015-01-26 um 11 43 01](https://cloud.githubusercontent.com/assets/186856/5898574/0fb5cf16-a551-11e4-9b52-862209e2773f.png)

**Comment by msom** [comment]
IE [ignores the visibility of pseudo elements](http://stackoverflow.com/questions/17530947/ie10-visibilityvisible-on-before-pseudo-element-of-visibilityhidden-eleme).

**Comment by maethu** [comment]
PR has been merged! Thx!
