### ISSUE TITLE
flyout navigation gets into infinite loop when not authorised on closed site

### ISSUE THREAD

**Issue by polyester** [OneGov/plonetheme.onegov#171]
The changes introduced in https://github.com/OneGov/plonetheme.onegov/commit/b53851b26742ee860806afa4ce86c1e9e99019a2#diff-6ac05f9f0a8265f8b265cf54bac54671 lead to an infinite loop of GET requests hammering the server, with corresponding high serverload and unability to login, if your site is shielded for any unauthorized access, for instance using iw.rejectanonymous. 

(if you still have a valid cookie, and thus logged in, it works)

**Comment by maethu** [comment]
@polyester Thanks for submitting this issue.

A check for 401 errors should solve the issue, right?

**Comment by polyester** [comment]
I'm far from the Javascript expert, but I would guess so. Willing to test on our setup.

**Comment by maethu** [comment]
Mee too :smile: 

But I now know what's the issue!

The beforetraverse hook in `iw.rejectanonymous` raises Unauthorized, which redirects to the login page (if not allready logged in). 

The `load_flyout_children` now gets the `login_form` (not 401), on the login form there are tabs and everything starts again.... and again... and again, well you experienced this :wink: flyoutChildren

I just pushed a branch (https://github.com/OneGov/plonetheme.onegov/tree/mle-fix-loop), with a fix, which makes sure the response of load_flyout_children is actually a flyout navigation. 

On my local machine, I'm no longer able to reproduce a infinite loop with plonetheme.onegov and iw.rejectanonymous.

**Comment by maethu** [comment]
@polyester If this works on your setup, I'll make a pull request and a new release asap.

**Comment by polyester** [comment]
@maethu confirmed: works on our setup (fully loaded site). Thanks!

**Comment by maethu** [comment]
@polyester thanks! PR is open https://github.com/OneGov/plonetheme.onegov/pull/172

**Comment by maethu** [comment]
@polyester https://pypi.python.org/pypi/plonetheme.onegov/1.5.3 contains this fix.
