### ISSUE TITLE
Move scss files to the according packages

### ISSUE THREAD

**Issue by maethu** [OneGov/plonetheme.onegov#173]
Always as soft dependency (zcml:condition):
- [x] Move solr part of search.scss into ftw.solr
- [x] Move blog.scss into ftw.blog
- [x] Move book.scss into ftw.book
- [x] [Move tabbedview.scss into ftw.tabbedview](https://github.com/4teamwork/ftw.tabbedview/pull/43) ftw.tabbedview 3.3.14!
- [x] Move directory.scss into seantis.dir.base
- [x] Move people.scss into seantis.people
- [x] Move reservation.scss into seantis.reservation
- [x] Move events.scss into seantis.dir.events
- [x] Move facility.scss into seantis.dir.facility

**Comment by msom** [comment]
Are you still working on this issue? I'm currently working on a visual redesign of the directories, events (not in this list) and reservations (there's already a pull request) modules and could therefore move the styles for these packages...

**Comment by shylux** [comment]
@msom Yes. I will create the pull requests and assign them to you.

**Comment by msom** [comment]
The changes in the plonetheme.onegov are in this branch: https://github.com/OneGov/plonetheme.onegov/tree/msom-issue-173
