### ISSUE TITLE
Global navigation with flyout of second level

### ISSUE THREAD

**Issue by ksuess** [OneGov/plonetheme.onegov#176]
> This theme comes with a flyout navigation. If you click on an element in the global navigation you get the children as a flyout navigation .... This behavior can be disabled in the plone.app.registry, using the setting plonetheme.onegov.flyout_navigation.

A client requested a flyout of the next level global navigation. Is it of general interest? If yes I would propose my code for merge here. Its some Javascript and CSS and an plone.app.registry entry to make this behavior optional.

![willkommen_ _schule_urdorf](https://cloud.githubusercontent.com/assets/1144737/7589324/40ec3a2e-f8c2-11e4-9d46-5dbfa0c4e333.png)

http://schuleurdorf.ch:10380/schuleurdorf

Nice theme and bundle! Great work, especially the stable responsive view and the subsite feature.

**Comment by maethu** [comment]
@ksuess 
Yes please :smiley:! It would be create if you could make a Pull-Request with your changes. So we can discuss the implementation and make sure old installations are upgradeable.
As you said the feature needs to be configurable and should be disabled by default.

> Nice theme and bundle! Great work, especially the stable responsive view and the subsite feature.

Thank you!

**Comment by ksuess** [comment]
The tests are not passing on [my change] (https://github.com/ksuess/plonetheme.onegov/commit/5d58c3677a507a13cf40fbc13573f9f66693f1fc) and not passing on master, what am I missing? 
[traceback snip](https://gist.github.com/ksuess/2643f45c8963a40c7a4e#file-gistfile1-txt)

**Comment by maethu** [comment]
@ksuess The ``master``looks fine on our CI --> https://jenkins.4teamwork.ch/view/All/job/plonetheme.onegov-master-test-plone-4.3.x.cfg/

**Comment by maethu** [comment]
Your fork produces the following test output on my machine:

```
Running ftw.testing.layer.MetaZCMLLayer tests:
  Set up ftw.testing.layer.ftw.testing:LAYER_CLEANUP in 0.000 seconds.
  Set up ftw.testing.layer.ftw.testing:ZCML_DIRECTIVES in 0.008 seconds.
  Set up ftw.testing.layer.MetaZCMLLayer in 0.004 seconds.
  Running:

  Ran 10 tests with 0 failures and 0 errors in 0.008 seconds.
Running plonetheme.onegov.testing.plonetheme.onegov:functional tests:
  Tear down ftw.testing.layer.MetaZCMLLayer in 0.000 seconds.
  Tear down ftw.testing.layer.ftw.testing:ZCML_DIRECTIVES in 0.000 seconds.
  Tear down ftw.testing.layer.ftw.testing:LAYER_CLEANUP in 0.000 seconds.
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.168 seconds.
  Set up plone.app.testing.layers.PloneFixture in 5.899 seconds.
  Set up ftw.builder.testing.BuilderLayer in 0.000 seconds.
  Set up plonetheme.onegov.testing.ThemeLayer in 2.591 seconds.
  Set up ftw.builder.testing.set_builder_session_factory in 0.000 seconds.
  Set up plonetheme.onegov.testing.plonetheme.onegov:functional in 0.000 seconds.
  Running:

  Ran 60 tests with 0 failures and 0 errors in 22.887 seconds.
Running plonetheme.onegov.testing.plonetheme.onegov:integration tests:
  Tear down plonetheme.onegov.testing.plonetheme.onegov:functional in 0.000 seconds.
  Tear down ftw.builder.testing.set_builder_session_factory in 0.000 seconds.
  Set up plonetheme.onegov.testing.plonetheme.onegov:integration in 0.000 seconds.
  Running:
    18/23 (78.3%)

Error in test test_markup_grandchildren (plonetheme.onegov.tests.test_load_flyout.TestFyloutView)
Traceback (most recent call last):
  File "/Users/maethu/.buildout/eggs-cache/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/private/tmp/plonetheme.onegov/plonetheme/onegov/tests/test_load_flyout.py", line 90, in test_markup_grandchildren
    subfolder = create(Builder('subfolder').within(folder))
  File "/Users/maethu/.buildout/eggs-cache/ftw.builder-1.6.3-py2.7.egg/ftw/builder/builder.py", line 19, in Builder
    builder_klass = registry.builder_registry.get(name)
  File "/Users/maethu/.buildout/eggs-cache/ftw.builder-1.6.3-py2.7.egg/ftw/builder/registry.py", line 16, in get
    raise KeyError('Unkown builder "%s"' % name)
KeyError: 'Unkown builder "subfolder"'


  Ran 23 tests with 0 failures and 1 errors in 1.765 seconds.
Running zope.testrunner.layer.UnitTests tests:
  Tear down plonetheme.onegov.testing.plonetheme.onegov:integration in 0.000 seconds.
  Tear down plonetheme.onegov.testing.ThemeLayer in 0.004 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.058 seconds.
  Tear down plone.testing.z2.Startup in 0.004 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.003 seconds.
  Tear down ftw.builder.testing.BuilderLayer in 0.000 seconds.
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
  Running:

  Ran 12 tests with 0 failures and 0 errors in 0.002 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
Total: 105 tests, 0 failures, 1 errors in 34.188 seconds.
```

There's no builodersubfolder, you can use just folder in your test.

**Comment by maethu** [comment]
@ksuess 
Well I now where the issue is. 

The plonetheme.onegov test suite als loads `ftw.solr`, for solr integration tests. 

Currently ftw.solr is not compatible with collective.solr 4.x. 
We still use collective.solr 3.x. So you need to pin down the collective.solr version for your local testing.

**Comment by ksuess** [comment]
@maethu 
Please, consider a merge.

**Comment by maethu** [comment]
:+1:  @jone ?

**Comment by jone** [comment]
:+1: thanks

**Comment by jone** [comment]
It's merged and released (`plonetheme.onegov = 1.7.0`).
Sorry for the delay, I was accidentally not watching the repository and didn't get any notifications :confused:
