### ISSUE TITLE
How to add new icons?

### ISSUE THREAD

**Issue by msom** [OneGov/plonetheme.onegov#184]
@ninfaj How can I add new icons to the theme? Has the font been generated with the icomoon app (https://icomoon.io/app/#/select)?

**Comment by ninfaj** [comment]
Yes the font is generated with icomoon.
Just download the svg file [icomoon.svg](https://raw.githubusercontent.com/OneGov/plonetheme.onegov/master/plonetheme/onegov/resources/fonts/icomoon.svg), import it into the [icomoon app](https://icomoon.io/app) and add your icons.

**Comment by msom** [comment]
Great, thanks!
